#### PyTorch Tensor Basics

In [49]:
import torch

In [50]:
torch.tensor(9)

tensor(9)

In [51]:
revenue = torch.tensor([100, 80, 54, 76])
revenue

tensor([100,  80,  54,  76])

In [52]:
revenue[:3]

tensor([100,  80,  54])

In [53]:
q1 = torch.tensor([
    [200, 220, 250],
    [150, 180, 210],
    [300, 330, 360]
])

q2 = torch.tensor([
    [209, 231, 260],
    [155, 192, 240],
    [302, 338, 390]
])

In [54]:
q1 + q2

tensor([[409, 451, 510],
        [305, 372, 450],
        [602, 668, 750]])

In [55]:
q2 - q1

tensor([[ 9, 11, 10],
        [ 5, 12, 30],
        [ 2,  8, 30]])

In [56]:
(q2 - q1) * 100 /q1

tensor([[ 4.5000,  5.0000,  4.0000],
        [ 3.3333,  6.6667, 14.2857],
        [ 0.6667,  2.4242,  8.3333]])

In [57]:
return_rate = 0.1
return_rate * q1

tensor([[20., 22., 25.],
        [15., 18., 21.],
        [30., 33., 36.]])

In [58]:
profit_per_unit = torch.tensor([
    [30, 27, 44],
    [22, 16, 41],
    [11, 22, 33]
])

In [59]:
profit_per_unit * q1

tensor([[ 6000,  5940, 11000],
        [ 3300,  2880,  8610],
        [ 3300,  7260, 11880]])

In [60]:
product_prices = torch.tensor([[1100, 650, 3200]])
product_prices

tensor([[1100,  650, 3200]])

In [61]:
torch.matmul(product_prices, q1)

tensor([[1277500, 1415000, 1563500]])

In [62]:
product_prices

tensor([[1100,  650, 3200]])

In [63]:
product_prices.t()  # Transpose

tensor([[1100],
        [ 650],
        [3200]])

In [64]:
prices_by_region = q1 * product_prices.t()
prices_by_region

tensor([[ 220000,  242000,  275000],
        [  97500,  117000,  136500],
        [ 960000, 1056000, 1152000]])

In [65]:
prices_by_region.sum(dim=0) #column wise sum

tensor([1277500, 1415000, 1563500])

In [66]:
units = torch.tensor([
    [200, 220],
    [150, 180],
    [300, 330]
])

In [67]:
units.shape

torch.Size([3, 2])

In [68]:
units.dtype

torch.int64

In [69]:
units.device

device(type='cpu')

In [70]:
units.view(-1)

tensor([200, 220, 150, 180, 300, 330])

In [71]:
units.view(2, 3)

tensor([[200, 220, 150],
        [180, 300, 330]])

In [72]:
units[2, 1]

tensor(330)

In [73]:
torch.rand(3, 4)

tensor([[0.6374, 0.3220, 0.6355, 0.9023],
        [0.3596, 0.0130, 0.4592, 0.6353],
        [0.9888, 0.8795, 0.0024, 0.4820]])