### Employee Bonus Prediction

#### Data Loading

In [1]:
import pandas as pd

# Load Data from CSV file

df = pd.read_csv("bonus.csv")
df.head()

,employee_id,performance,years_of_experience,projects_completed,bonus
0,EMP_001,7,1,3,116
1,EMP_002,4,8,10,136
2,EMP_003,8,4,5,150
3,EMP_004,5,4,7,118
4,EMP_005,7,5,6,146


In [2]:
df.shape

(1000, 5)

#### Train Test Split the Data

In [3]:
from sklearn.model_selection import train_test_split

# Separate features and target
X = df[['performance', 'years_of_experience', 'projects_completed']].values
y = df[['bonus']].values  # Ensure target is a 2D array for compatibility

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [4]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(800, 3)
(200, 3)
(800, 1)
(200, 1)


#### Converting To Tensors

In [5]:
import torch
import torch.nn as nn
import torch.optim as optim

# Seed for reproducibility
torch.manual_seed(0)

# Convert to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

### Neural Network Class

In [6]:
class BonusPredictor(nn.Module):
    def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(3, 1)     # 3 input features, 1 output feature
        )

    def forward(self, x):
        return self.network(x)

In [10]:
model = BonusPredictor()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr = 0.005)

#### NN Training

In [11]:
epochs = 5000

for epoch in range(epochs):

    # 1 Forward Pass
    predictions = model(X_train_tensor)
    loss = criterion(predictions, y_train_tensor)

    # 2 Backpropagation
    optimizer.zero_grad()
    loss.backward()

    # 3 Update weights
    optimizer.step()


    # Print Loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch + 1} / {epochs}], Loss: {loss.item(): .2f}") 

Epoch [100 / 5000], Loss:  20.12
Epoch [200 / 5000], Loss:  17.52
Epoch [300 / 5000], Loss:  15.36
Epoch [400 / 5000], Loss:  13.50
Epoch [500 / 5000], Loss:  11.88
Epoch [600 / 5000], Loss:  10.46
Epoch [700 / 5000], Loss:  9.21
Epoch [800 / 5000], Loss:  8.11
Epoch [900 / 5000], Loss:  7.14
Epoch [1000 / 5000], Loss:  6.28
Epoch [1100 / 5000], Loss:  5.53
Epoch [1200 / 5000], Loss:  4.87
Epoch [1300 / 5000], Loss:  4.29
Epoch [1400 / 5000], Loss:  3.78
Epoch [1500 / 5000], Loss:  3.32
Epoch [1600 / 5000], Loss:  2.93
Epoch [1700 / 5000], Loss:  2.58
Epoch [1800 / 5000], Loss:  2.27
Epoch [1900 / 5000], Loss:  2.00
Epoch [2000 / 5000], Loss:  1.76
Epoch [2100 / 5000], Loss:  1.55
Epoch [2200 / 5000], Loss:  1.36
Epoch [2300 / 5000], Loss:  1.20
Epoch [2400 / 5000], Loss:  1.06
Epoch [2500 / 5000], Loss:  0.93
Epoch [2600 / 5000], Loss:  0.82
Epoch [2700 / 5000], Loss:  0.72
Epoch [2800 / 5000], Loss:  0.64
Epoch [2900 / 5000], Loss:  0.56
Epoch [3000 / 5000], Loss:  0.49
Epoch [3100 /

#### NN Evaluation

In [12]:
model.eval()

with torch.no_grad():
    test_predictions = model(X_test_tensor)
    test_loss = criterion(test_predictions, y_test_tensor)

print(f"Test Loss: {test_loss.item():.2f}")

Test Loss: 0.04


In [13]:
X_test_tensor[:3]

tensor([[ 8.,  9., 10.],
        [ 9.,  2.,  5.],
        [ 3.,  7.,  8.]])

In [14]:
test_predictions[:3]

tensor([[189.9594],
        [150.1504],
        [113.7402]])

In [15]:
y_test_tensor[:3]

tensor([[190.],
        [150.],
        [114.]])

In [16]:
# Actual weights and Bias
# w1 = 12, w2 = 6, w3 = 2, bias = 20

for name, val in model.named_parameters():
    print(f"Name: {name}, Value: {val}")

Name: network.0.weight, Value: Parameter containing:
tensor([[12.0322,  5.8480,  2.1810]], requires_grad=True)
Name: network.0.bias, Value: Parameter containing:
tensor([19.2592], requires_grad=True)
